;;; Copyright (c) 2012-2013, Alvaro Castro-Castilla. All rights reserved.
;;; Functional programming procedures

(##namespace ("crypto:digest#"
              digest-u8vector
              digest-subu8vector
              digest-ansi-string
              digest-ansi-substring
              digest-string
              digest-substring
              digest-file
              crc32
              md5
              sha-1
              sha-224
              sha-256
              digest-update-u32-be
              digest-update-u32-le
              digest-update-u16-be
              digest-update-u16-le
              digest-update-u8
              get-zero-u8vector
              zero-u8vector
              digest-update-subu8vector
              close-digest
              open-digest
              open-digest-sha-256
              open-digest-sha-224
              digest-update-sha-256
              hash-block-init-sha-256
              hash-block-init-sha-224
              open-digest-sha-1
              digest-update-sha-1
              hash-block-init-sha-1
              open-digest-md5
              digest-update-md5
              hash-block-init-md5
              digest-update-block-digest
              end-block-digest
              process-last-block
              convert-hash-block
              block-digest-width-set!
              block-digest-width
              block-digest-big-endian?-set!
              block-digest-big-endian?
              block-digest-bit-pos-set!
              block-digest-bit-pos
              block-digest-block-pos-set!
              block-digest-block-pos
              block-digest-block-set!
              block-digest-block
              block-digest-hash-set!
              block-digest-hash
              block-digest-hash-update-set!
              block-digest-hash-update
              block-digest?
              make-block-digest
              hash-block->u8vector
              hash-block->hex-string
              open-digest-crc32
              end-crc32
              digest-update-crc32
              crc32-table
              crc32-digest-lo16-set!
              crc32-digest-lo16
              crc32-digest-hi16-set!
              crc32-digest-hi16
              crc32-digest?
              make-crc32-digest
              digest-state-set!
              digest-state
              digest-update-set!
              digest-update
              digest-end-set!
              digest-end
              digest?
              make-digest
              ))

(##namespace (""
              string->utf8-u8vector
              substring->utf8-u8vector
              ))

